# Travis CI script

language: c
compiler:
- clang
- gcc

sudo: required

env:
- ROLE=client BOARD=ml605 AUTOTOOLS_CFG=with_autotools EPICS_CFG=with_epics
- ROLE=client BOARD=afcv3 AUTOTOOLS_CFG=with_autotools EPICS_CFG=with_epics
- ROLE=server BOARD=ml605 AUTOTOOLS_CFG=with_autotools EPICS_CFG=with_epics
- ROLE=server BOARD=afcv3 AUTOTOOLS_CFG=with_autotools EPICS_CFG=with_epics
- ROLE=gateware

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
