# Travis CI script

dist: trusty

language: c
compiler:
- clang
- gcc

sudo: required

env:
- HALCS_BUILD_SYSTEM=makefile ROLE=client BOARD=ml605
- HALCS_BUILD_SYSTEM=makefile ROLE=client BOARD=afcv3
- HALCS_BUILD_SYSTEM=makefile ROLE=client BOARD=afcv3_1
- HALCS_BUILD_SYSTEM=makefile ROLE=server BOARD=ml605
- HALCS_BUILD_SYSTEM=makefile ROLE=server BOARD=afcv3
- HALCS_BUILD_SYSTEM=makefile ROLE=server BOARD=afcv3_1
- ROLE=gateware

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- $CC --version
- which $CC
# workaround clang not system wide, fail on sudo make install
- export CC=`which $CC`
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
