# Travis CI script

dist: trusty

language: c
compiler:
- clang
- gcc

sudo: required

env:
- ROLE=client BOARD=ml605
- ROLE=client BOARD=afcv3
- ROLE=client BOARD=afcv3_1
- ROLE=server HALCS_KERNEL_DIR=/lib/modules/$(uname -r)/build HALCS_DRIVER_INSTALL_DIR=/lib/modules/$(uname -r)/extra BOARD=ml605
- ROLE=server HALCS_KERNEL_DIR=/lib/modules/$(uname -r)/build HALCS_DRIVER_INSTALL_DIR=/lib/modules/$(uname -r)/extra BOARD=afcv3
- ROLE=server HALCS_KERNEL_DIR=/lib/modules/$(uname -r)/build HALCS_DRIVER_INSTALL_DIR=/lib/modules/$(uname -r)/extra BOARD=afcv3_1
- ROLE=gateware

addons:
  apt:
    packages:
    - uuid-dev

before_install:
- $CC --version
- which $CC
# workaround clang not system wide, fail on sudo make install
- export CC=`which $CC`
- git submodule update --init --recursive

#   Build and check this project
script:
- ./ci_build.sh
