# Travis CI script

language: c
compiler:
- clang
- gcc

env:
- ROLE=client BOARD=ml605
- ROLE=client BOARD=afcv3
- ROLE=server BOARD=ml605
- ROLE=server BOARD=afcv3
- ROLE=gateware

before_install:
- git submodule update --init --recursive

#   Build-check-install all subprojects
before_script:
- sudo apt-get install uuid-dev

#   Build and check this project
script:
- ./ci_build.sh
