#!/bin/sh

#EPICS
export EPICS_HOST_ARCH=linux-x86_64
export EPICS_FOLDER=/opt/epics
export EPICS_BASE=${EPICS_FOLDER}/base
export EPICS_TOPDIR=${EPICS_BASE}
export EPICS_BIN=${EPICS_BASE}/bin/${EPICS_HOST_ARCH}
#export EPICS_CA_ADDR_LIST="127.0.0.1 10.2.117.255 10.2.105.255 10.0.17.255"
#export EPICS_CA_AUTO_ADDR_LIST="YES"
export LINUX_HOSTNAME=$(hostname)
export EPICS_HOSTNAME="SIDI-BPM-01"
export BPM_EPICS_STARTUP=${EPICS_FOLDER}/startup/ioc/bpm-epics-ioc/iocBoot/iocBPM

export EPICS_EXTENSIONS=${EPICS_FOLDER}/extensions
export EPICS_EXTENSIONS_BIN=${EPICS_FOLDER}/extensions/bin/${EPICS_HOST_ARCH}
export EPICS_CA_MAX_ARRAY_BYTES=50000000

PATH=${PATH}:${EPICS_BIN}:${EPICS_EXTENSIONS}:${EPICS_EXTENSIONS_BIN}
