#!/usr/bin/env bash

# Repo versions
LIBSODIUM_VERSION=1.0.8
LIBZMQ_VERSION=v4.2.5
CZMQ_VERSION=v4.0.2
MALAMUTE_VERSION=v1.6.1
HALCS_VERSION=v1.9.1
HALCS_LIBS_VERSION=v1.9.1
BPM_SW_CLI_VERSION=master
BPM_EPICS_IOC_VERSION=v2.8.0
BPM_GW_VERSION=v2.3.1
BPM_IPMI_VERSION=master
HALCS_GENERIC_UDEV_VERSION=master
