#!/usr/bin/env python3

'''
Author: Érico Nogueira
'''

from argparse import ArgumentParser
from pickle import dump
from time import sleep

import numpy as np
from scipy.io import savemat

from bpm_app.pvs import create_pv, put_pv, get_pv, wait_for_pv_connection, wait_pv
from bpm_app.sirius import rtmlamp_slot, get_pv_prefix, crate_number, rtmlamp_channels, get_rtmlamp_prefix

parser = ArgumentParser(
        'acquire_lamp',
        'Acquire and save RTM-LAMP data')
parser.add_argument('output_file')
parser.add_argument('--mat-file')
parser.add_argument('--voltage-step', type=float)
parser.add_argument('--current-step', type=float)
parser.add_argument('--despike', type=float)
parser.add_argument('--single-crate', type=int)
parser.add_argument('--only-main-channels', action='store_true')
parser.add_argument('--samples', type=int, default=100_000)
parser.add_argument('--samples-pre', type=int, default=100)
parser.add_argument('--no-trigger', action='store_true')
parser.add_argument('--now', action='store_true')

args = parser.parse_args()

out_file = args.output_file
out_mat_file = args.mat_file

voltage_step = args.voltage_step
current_step = args.current_step

despike_threshold = args.despike

if args.only_main_channels:
    rtmlamp_channels = rtmlamp_channels[:8]

samples_val = args.samples
samples_pre_val = args.samples_pre

voltage_step_b = voltage_step is not None
current_step_b = current_step is not None

if args.single_crate is None:
    crates_n = range(1, 21)
else:
    crates_n = [args.single_crate]

if voltage_step_b and current_step_b:
    raise "Can't use both voltage and current steps at the same time"

control_ps = voltage_step_b or current_step_b

no_trigger = args.no_trigger
acq_now = args.now

lamp_triggers = [0, 4]
lamp_trigger_source = 5

def despiker(array, thres):
    for idx in range(len(array)):
        if idx == 0:
            # Assumes no spike on index 0
            continue
        else:
            if abs(array[idx] - array[idx - 1]) > thres:
                array[idx] = array[idx - 1]

trigger_type = []
trigger_rep = []
trigger_event = []
samples_pre = []
samples_post = []

trigger_mux_sel = []
trigger_mux_src = []

trig_en = []
voltage_sp = []
current_sp = []
curr_loop_mode = []
pwr_state = []

current_data = {}
voltage_data = {}

crates = [crate_number(i) for i in crates_n]
for crate in crates:
    prefix = get_pv_prefix(crate, rtmlamp_slot)

    trigger_type.append(create_pv(prefix + f'LAMPTrigger-Sel'))
    trigger_rep.append(create_pv(prefix + f'LAMPTriggerRep-Sel'))
    trigger_event.append(create_pv(prefix + f'LAMPTriggerEvent-Cmd'))
    samples_pre.append(create_pv(prefix + f'LAMPSamplesPre-SP'))
    samples_post.append(create_pv(prefix + f'LAMPSamplesPost-SP'))

    trigger_mux_sel.extend((create_pv(prefix + f'TRIGGER_LAMP{i}RcvInSel-SP') for i in lamp_triggers))
    trigger_mux_src.extend((create_pv(prefix + f'TRIGGER_LAMP{i}RcvSrc-Sel') for i in lamp_triggers))

    voltage_data[crate] = []
    current_data[crate] = []

    for channel in rtmlamp_channels:
        rprefix = get_rtmlamp_prefix(crate, channel)

        trig_en.append(create_pv(rprefix + 'TrigEn-Sel'))
        voltage_sp.append(create_pv(rprefix + 'Voltage-SP'))
        current_sp.append(create_pv(rprefix + 'Current-SP'))
        curr_loop_mode.append(create_pv(rprefix + 'CurrLoopMode-Sel'))
        pwr_state.append(create_pv(rprefix + 'PwrState-Sel'))

        voltage_data[crate].append(create_pv(rprefix + 'LAMPVoltageData'))
        current_data[crate].append(create_pv(rprefix + 'LAMPCurrentData'))

all_data = []
for i, v in zip(current_data.values(), voltage_data.values()):
    all_data.extend(i)
    all_data.extend(v)

fofb_event = create_pv("AS-RaMO:TI-EVG:Evt10ExtTrig-Cmd")

wait_for_pv_connection()

# setup acq
put_pv(trigger_type, 0 if acq_now else 1, wait=False, check=False)
put_pv(trigger_rep, 0, wait=False, check=False)
if acq_now:
    put_pv(samples_pre, samples_val, wait=False, check=False)
    put_pv(samples_post, 0, wait=False, check=False)
else:
    put_pv(samples_pre, samples_pre_val, wait=False, check=False)
    put_pv(samples_post, samples_val - samples_pre_val, wait=False, check=False)
put_pv(trigger_event, 1, wait=False)

# setup triggering
put_pv(trigger_mux_src, 0, wait=False)
put_pv(trigger_mux_sel, lamp_trigger_source, wait=False)

# reset rtmlamp
if control_ps:
    put_pv(trig_en, 0, wait=False);
    put_pv(voltage_sp, 0, wait=False);
    put_pv(current_sp, 0, wait=False);
    put_pv(curr_loop_mode, 0 if voltage_step_b else 2, wait=False);
    put_pv(pwr_state, 1, wait=False);

wait_pv()

if control_ps:
    put_pv(trig_en, 1);

if voltage_step_b:
    put_pv(voltage_sp, voltage_step, check=False);
elif current_step_b:
    put_pv(current_sp, current_step, check=False);
wait_pv()

def get_data_timestamps(data):
    return np.array([pv.sp.get_timevars()['timestamp'] for pv in data])
all_data_timestamps_initial = get_data_timestamps(all_data)

put_pv(trigger_event, 0)
sleep(1)

if control_ps and not no_trigger:
    put_pv([fofb_event], 1)

print('Waiting for array data to be updated')
while np.any(get_data_timestamps(all_data) == all_data_timestamps_initial):
    sleep(1)

if control_ps:
    put_pv(trig_en, 0)
    put_pv(voltage_sp, 0, wait=False)
    put_pv(current_sp, 0, wait=False)
    wait_pv()

data = {'current_step': current_step, 'voltage_step': voltage_step, 'samples_pre': samples_val if acq_now else samples_pre_val}
data['current'] = np.zeros((samples_val, len(crates) * len(rtmlamp_channels)))
data['voltage'] = np.zeros((samples_val, len(crates) * len(rtmlamp_channels)))
for i, crate in enumerate(crates):
    i_data = np.array(get_pv(current_data[crate]))
    v_data = np.array(get_pv(voltage_data[crate]))
    if despike_threshold:
        for j in range(len(i_data)):
            despiker(i_data[j], despike_threshold)
    data['current'][:,i * len(rtmlamp_channels):(i+1) * len(rtmlamp_channels)] = i_data.T
    data['voltage'][:,i * len(rtmlamp_channels):(i+1) * len(rtmlamp_channels)] = v_data.T

with open(out_file, 'wb') as f:
    dump(data, f)

# clean up values so they can be saved
if current_step is None:
    data['current_step'] = 0
if voltage_step is None:
    data['voltage_step'] = 0

if out_mat_file is not None:
    savemat(out_mat_file, data)
