#!/usr/bin/env python3

'''
Author: Érico Nogueira
'''

import sys

from bpm_app.pvs import create_pv, wait_for_pv_connection, put_pv, wait_pv, get_pv

bpm_name = sys.argv[1]

antennas = ['A', 'B', 'C', 'D']

dir_gains = [create_pv(bpm_name + f':SwDirGain{antenna}-SP') for antenna in antennas]
inv_gains = [create_pv(bpm_name + f':SwInvGain{antenna}-SP') for antenna in antennas]

wait_for_pv_connection()

dir_gains_vals = get_pv(dir_gains)
inv_gains_vals = get_pv(inv_gains)

for pv, val in zip(dir_gains, inv_gains_vals):
    put_pv([pv], val, check=False)
for pv, val in zip(inv_gains, dir_gains_vals):
    put_pv([pv], val, check=False)
