#!/usr/bin/env python3

'''Set all BPM antenna gains to ~1.

Author: Érico Nogueira
'''

from bpm_app.pvs import create_pv, wait_for_pv_connection, put_pv
from bpm_app.sirius import rtmlamp_slot, slots_by_crate, crate_number, get_pv_prefix

max_multiplier = 0xffffff / (1<<24)

# TODO: add crate 21
crates = [crate_number(i) for i in range(1, 21)]

gains = []

for crate in crates:
    for slot in slots_by_crate[crate]:
        if slot == rtmlamp_slot:
            continue

        prefix = get_pv_prefix(crate, slot)
        for l in ['A','B','C','D']:
            for cycle in ['Inv', 'Dir']:
                gains.append(create_pv(prefix + f'Sw{cycle}Gain{l}-SP'))

wait_for_pv_connection()
# TODO: deal with floating point and DRVH limits
put_pv(gains, max_multiplier, check=False)
