#!/usr/bin/env python3

'''Save antenna readings from BPMs. Run as:

    ./save_bpm_antennas out.pickle

Author: Érico Nogueira
'''

import sys
from pickle import dump

import numpy as np

from bpm_app.pvs import create_pv, wait_for_pv_connection, get_pv
from bpm_app.sirius import si_bpm_slots, first_si_bpm_slot, crate_number, get_pv_prefix

file_name = sys.argv[1]

crates = [crate_number(i) for i in range(1, 21)]

pvs_per_bpm = {}
xgains = {}
ygains = {}

for crate in crates:
    for slot in si_bpm_slots[crate]:
        # ignore ID BPMs
        if slot < first_si_bpm_slot:
            continue

        key = (crate, slot)

        prefix = get_pv_prefix(crate, slot)
        bpm_pvs = {}
        for l in ['a','b','c','d']:
            bpm_pvs[l] = create_pv(prefix + f'GEN_{l.upper()}ArrayData')

        bpm_pvs['xgain'] = create_pv(prefix + 'PosKx-RB')
        bpm_pvs['ygain'] = create_pv(prefix + 'PosKy-RB')

        pvs_per_bpm[key] = bpm_pvs

wait_for_pv_connection()

data = {}
for key in pvs_per_bpm:
    data[key] = {}
    for l in pvs_per_bpm[key]:
        data[key][l] = get_pv([pvs_per_bpm[key][l]])[0]

with open(file_name, 'wb') as f:
    dump(data, f)
