#!/usr/bin/env python3

'''Test that attenuation PVs for all RFFEs on a given crate are working

    ./test_rffes crate ...

Author: Érico Nogueira
'''

import sys

from bpm_app.pvs import create_pv, wait_for_pv_connection, put_pv
from bpm_app.sirius import all_bpm_slots, get_pv_prefix, crate_number

crates = sys.argv[1:]
pvs = []

for crate in crates:
    for slot in all_bpm_slots[crate_number(crate)]:
        prefix = get_pv_prefix(crate, slot)
        pvs.append(create_pv(prefix + 'RFFEAtt-SP'))

wait_for_pv_connection()

put_pv(pvs, 6)
put_pv(pvs, 0)
